name: Simple pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.10'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install flake8
      
          - name: Lint code
            run: |
              flake8 lab4/ --ignore=W291,E501,E305,W293,E302,W292

          - name: Run tests
            run: python -m unittest discover -p "*Tests.py"
            
          - name: Log in to Docker Hub
            run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
          - name: Build Docker image
            run: docker build -t darenky/tests ./Lab4

          - name: Push image to Docker Hub
            run: docker push darenky/tests

          - name: Run tests in Docker container
            run: docker run darenky/tests